//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Italika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_ITALIKAS
    {
        public int ID_ITALIKA { get; set; }
        public string SKU { get; set; }
        public string FERT { get; set; }
        public string MODELO { get; set; }
        public string TIPO { get; set; }
        public string NUM_SERIE { get; set; }
        public System.DateTime FECHA { get; set; }
    }
}
