//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Italika.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BRANCHBITEntities : DbContext
    {
        public BRANCHBITEntities()
            : base("name=BRANCHBITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BR_ITALIKAS> BR_ITALIKAS { get; set; }
    
        public virtual ObjectResult<BR_ITALIKAS> BuscarItalika(Nullable<int> iD_ITALIKA, string bUSCAR)
        {
            var iD_ITALIKAParameter = iD_ITALIKA.HasValue ?
                new ObjectParameter("iD_ITALIKA", iD_ITALIKA) :
                new ObjectParameter("iD_ITALIKA", typeof(int));
    
            var bUSCARParameter = bUSCAR != null ?
                new ObjectParameter("bUSCAR", bUSCAR) :
                new ObjectParameter("bUSCAR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BR_ITALIKAS>("BuscarItalika", iD_ITALIKAParameter, bUSCARParameter);
        }
    
        public virtual ObjectResult<BR_ITALIKAS> BuscarItalika(Nullable<int> iD_ITALIKA, string bUSCAR, MergeOption mergeOption)
        {
            var iD_ITALIKAParameter = iD_ITALIKA.HasValue ?
                new ObjectParameter("iD_ITALIKA", iD_ITALIKA) :
                new ObjectParameter("iD_ITALIKA", typeof(int));
    
            var bUSCARParameter = bUSCAR != null ?
                new ObjectParameter("bUSCAR", bUSCAR) :
                new ObjectParameter("bUSCAR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BR_ITALIKAS>("BuscarItalika", mergeOption, iD_ITALIKAParameter, bUSCARParameter);
        }
    }
}
